### ISSUE TITLE
Custom dataset Linear Eval 

### ISSUE THREAD

**Issue by letdivedeep** [facebookresearch/msn#13]
@MidoAssran  and team great work !!!

I will like to use this for my custom dataset to build a linear classification model.  I started the model on my custom dataset by modifying the config/pretrain/msn_vits16.yaml
 ```
criterion:
  ent_weight: 0.0
  final_sharpen: 0.25
  me_max: true
  memax_weight: 1.0
  num_proto: 1024
  start_sharpen: 0.25
  temperature: 0.1
  batch_size: 64
  use_ent: true
  use_sinkhorn: true
data:
  color_jitter_strength: 0.5
  pin_mem: true
  num_workers: 10
  image_folder: custom_db/
  label_smoothing: 0.0
  patch_drop: 0.15
  rand_size: 224
  focal_size: 96
  rand_views: 1
  focal_views: 10
  root_path: dataset/
logging:
  folder: saved_models/msn_os_logs/
  write_tag: msn-experiment-1
meta:
  bottleneck: 1
copy_data: false
  drop_path_rate: 0.0
  hidden_dim: 2048
  load_checkpoint: false
  model_name: deit_small
  output_dim: 256
  read_checkpoint: null
  use_bn: true
  use_fp16: false
  use_pred_head: false
optimization:
  clip_grad: 3.0
  epochs: 350
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  lr: 0.001
  start_lr: 0.0002
  warmup: 15
  weight_decay: 0.04
```
and start the model pre-training using this cmd 
`python main.py --fname configs/pretrain/msn_vits16.yaml  --devices cuda:0`

was able to start the model training as seen in the below screenshots 
![pretrain_logs](https://user-images.githubusercontent.com/74127861/183444113-323d7012-a87b-4a35-9946-769fdf069dc7.png)

### 2) Downstream Task of Linear Classifier 
confused on how to start the downstream task of image classification 
Question : 
- How to start the model training using a linear classifier on a custom dataset without distributed training?
- How to structure the dataset : dataset> custom_db > cls_id > images  will this pattern work ? 

Any help will be appreciated
